version: '3.8'

services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # Sync project dir with container web dir
    ports:
      - "80:80"
      - "443:443" # For future SSL traffic
    

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: e-commerce
      MYSQL_PASSWORD: e-commerce123 # this should live in a env var
      MYSQL_ALLOW_EMPTY_PASSWORD: "1" # equivalent to True
    
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistint sql files with container


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
